<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                      http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.neo4j.driver</groupId>
        <artifactId>neo4j-java-driver-parent</artifactId>
        <version>6.3-SNAPSHOT</version>
    </parent>

    <artifactId>neo4j-java-driver-encryption</artifactId>

    <packaging>pom</packaging>
    <name>Neo4j Java Driver (Encryption)</name>
    <description>Parent project for encryption implementations.</description>

    <modules>
        <module>google-cloud-kms</module>
        <module>aws-kms</module>
        <module>azure-keyvault</module>
        <module>kyber</module>
    </modules>

    <scm>
        <connection>scm:git:git://github.com/neo4j/neo4j-java-driver.git</connection>
        <developerConnection>scm:git:git@github.com:neo4j/neo4j-java-driver.git</developerConnection>
        <url>https://github.com/neo4j/neo4j-java-driver</url>
    </scm>

</project>
