!: BOLT 3
!: AUTO RESET

C: HELLO {"scheme": "none", "user_agent": "neo4j-java/dev"}
S: SUCCESS {"server": "Neo4j/9.9.9", "connection_id": "bolt-123456789"}
C: RUN "CALL dbms.cluster.routing.getRoutingTable({context})" {"context": {}} {}
   PULL_ALL
S: SUCCESS {"fields": ["ttl", "servers"]}
   RECORD [9223372036854775807, [{"addresses": ["127.0.0.1:9004"],"role": "WRITE"}, {"addresses": ["127.0.0.1:9005","127.0.0.1:9006"], "role": "READ"},{"addresses": ["127.0.0.1:9001"], "role": "ROUTE"}]]
   SUCCESS {}
C: RUN "CALL dbms.cluster.routing.getRoutingTable({context})" {"context": {}} {}
   PULL_ALL
S: SUCCESS {"fields": ["ttl", "servers"]}
   RECORD [9223372036854775807, [{"addresses": ["127.0.0.1:9004"],"role": "WRITE"}, {"addresses": ["127.0.0.1:9005","127.0.0.1:9006"], "role": "READ"},{"addresses": ["127.0.0.1:9001"], "role": "ROUTE"}]]
   SUCCESS {}
C: RUN "CALL dbms.cluster.routing.getRoutingTable({context})" {"context": {}} {}
   PULL_ALL
S: SUCCESS {"fields": ["ttl", "servers"]}
   RECORD [9223372036854775807, [{"addresses": [],"role": "WRITE"}, {"addresses": ["127.0.0.1:9005","127.0.0.1:9006"], "role": "READ"},{"addresses": ["127.0.0.1:9001"], "role": "ROUTE"}]]
   SUCCESS {}
C: RUN "CALL dbms.cluster.routing.getRoutingTable({context})" {"context": {}} {}
   PULL_ALL
S: SUCCESS {"fields": ["ttl", "servers"]}
   RECORD [9223372036854775807, [{"addresses": ["127.0.0.1:9008"],"role": "WRITE"}, {"addresses": ["127.0.0.1:9005","127.0.0.1:9006"], "role": "READ"},{"addresses": ["127.0.0.1:9001"], "role": "ROUTE"}]]
   SUCCESS {}
