!: BOLT 3
!: AUTO RESET
!: AUTO GOODBYE

C: HELLO {"scheme": "none", "user_agent": "neo4j-java/dev"}
S: SUCCESS {"server": "Neo4j/3.5.0", "connection_id": "bolt-123456789"}
C: RESET
S: SUCCESS {}
C: BEGIN {"bookmarks": ["neo4j:bookmark:v1:tx0"]}
S: SUCCESS {}
C: RUN "RETURN 1" {} {}
   PULL_ALL
S: FAILURE {"code": "Neo.TransientError.General.DatabaseUnavailable", "message": "Database shut down."}
S: <EXIT>
