!: AUTO INIT
!: AUTO RESET
!: AUTO RUN "RETURN 1 // JavaDriver poll to test connection" {}
!: AUTO PULL_ALL

C: RUN "CREATE (n {name:'Bob'})" {}
   PULL_ALL
S: SUCCESS {}
   SUCCESS {}
C: RUN "BEGIN" {}
   PULL_ALL
   RUN "CREATE (n {name:'Alice'})" {}
   PULL_ALL
S: SUCCESS {}
   SUCCESS {}
   SUCCESS {}
   SUCCESS {}
C: RUN "CREATE (n {name:'Tina'})" {}
   PULL_ALL
S: SUCCESS {}
   SUCCESS {}
C: RUN "COMMIT" {}
   PULL_ALL
S: SUCCESS {}
   SUCCESS {}

C: RUN "MATCH (n) RETURN n.name" {}
   PULL_ALL
S: SUCCESS {"fields": ["n.name"]}
   RECORD ["Bob"]
   RECORD ["Alice"]
   RECORD ["Tina"]
   SUCCESS {}
