!: BOLT 3
!: AUTO RESET
!: AUTO HELLO
!: AUTO GOODBYE

C: RUN "CALL dbms.cluster.routing.getRoutingTable($context)" {"context": {"address": "127.0.0.1:9001"}} {}
   PULL_ALL
S: SUCCESS {"fields": ["ttl", "servers"]}
   RECORD [9223372036854775807, [{"addresses": ["127.0.0.1:9001", "127.0.0.1:9002"],"role": "WRITE"}, {"addresses": ["127.0.0.1:9001", "127.0.0.1:9002"], "role": "READ"},{"addresses": ["127.0.0.1:9001", "127.0.0.1:9002"], "role": "ROUTE"}]]
   SUCCESS {}
C: RUN "MATCH (n) RETURN n.name AS name" {} {}
   PULL_ALL
S: SUCCESS {"fields": ["name"]}
   RECORD ["Alice"]
   RECORD ["Bob"]
   RECORD ["Eve"]
   SUCCESS {}
S: <EXIT>
