!: AUTO INIT
!: AUTO RESET
!: AUTO RUN "RETURN 1 // JavaDriver poll to test connection" {}
!: AUTO PULL_ALL

C: RUN "CALL dbms.cluster.routing.getServers" {}
   PULL_ALL
S: SUCCESS {"fields": ["ttl", "servers"]}
   RECORD [9223372036854775807, [{"addresses": ["127.0.0.1:9001","127.0.0.1:9003"], "role": "ROUTE"},{"addresses": ["127.0.0.1:9002"], "role": "READ"},{"addresses": ["127.0.0.1:9003"], "role": "WRITE"}]]
   SUCCESS {}
C: RUN "CALL dbms.cluster.routing.getServers" {}
   PULL_ALL
S: SUCCESS {"fields": ["ttl", "servers"]}
   RECORD [9223372036854775807, [{"addresses": ["127.0.0.1:9004"], "role": "ROUTE"},{"addresses": ["127.0.0.1:9005"], "role": "READ"},{"addresses": ["127.0.0.1:9006"], "role": "WRITE"}]]
   SUCCESS {}
