!: BOLT 4
!: AUTO RESET
!: AUTO BEGIN
!: AUTO HELLO
!: AUTO GOODBYE
!: AUTO ROLLBACK

C: RUN "RETURN 1" {} {}
   PULL {"n": 1000}
S: FAILURE {"code": "Neo.ClientError.Cluster.NotALeader", "message": "blabla"}
   IGNORED
C: RUN "RETURN 1" {} {}
   PULL {"n": 1000}
S: SUCCESS {"fields": ["1"]}
   RECORD [1]
   SUCCESS {}
C: RUN "MATCH (n) RETURN n.name" {} {}
   PULL {"n": 1000}
S: SUCCESS {"fields": ["n.name"]}
   RECORD ["Foo"]
   RECORD ["Bar"]
   SUCCESS {}
C: COMMIT
S: SUCCESS {"bookmark": "NewBookmark"}
   <EXIT>
