!: BOLT 3
!: AUTO GOODBYE

C: HELLO {"scheme": "none", "user_agent": "neo4j-java/dev"}
S: SUCCESS {"server": "Neo4j/3.5.0", "connection_id": "bolt-123456789"}
C: RESET
S: SUCCESS {}
C: RUN "RETURN 42 AS answer" {} {}
   PULL_ALL
S: SUCCESS {"fields": ["answer"]}
   RECORD [42]
   SUCCESS {}
C: RESET
S: FAILURE {"code": "Neo.TransientError.General.DatabaseUnavailable", "message": "Unable to reset"}
   <EXIT>
