!: BOLT 3
!: AUTO RESET
!: AUTO GOODBYE

C: HELLO {"scheme": "none", "user_agent": "neo4j-java/dev"}
S: SUCCESS {"server": "Neo4j/3.5.0", "connection_id": "bolt-123456789"}
C: BEGIN {}
S: SUCCESS {}
C: RUN "CREATE (n {name:'Alice'}) RETURN n.name AS name" {} {}
   PULL_ALL
S: SUCCESS {"fields": ["name"]}
   RECORD ["Alice"]
   SUCCESS {}
C: ROLLBACK
S: FAILURE {"code": "Neo.TransientError.General.DatabaseUnavailable", "message": "Unable to rollback"}
C: RESET
S: SUCCESS {}
