!: AUTO INIT
!: AUTO RESET
!: AUTO RUN "RETURN 1 // JavaDriver poll to test connection" {}
!: AUTO PULL_ALL

C: RUN "CALL dbms.cluster.routing.getServers" {}
   PULL_ALL
S: SUCCESS {"fields": ["ttl", "servers"]}
   RECORD [120, [{"addresses": ["127.0.0.1:9011"],"role": "WRITE"}, {"addresses": ["127.0.0.1:9021","127.0.0.1:9022","127.0.0.1:9023"], "role": "READ"},{"addresses": ["127.0.0.1:9001","127.0.0.1:9002"], "role": "ROUTE"}]]
   SUCCESS {}
