!: BOLT 3
!: AUTO RESET
!: AUTO GOODBYE

C: HELLO {"scheme": "none", "user_agent": "neo4j-java/dev"}
S: SUCCESS {"server": "Neo4j/3.5.0", "connection_id": "bolt-123456789"}
C: BEGIN {"bookmarks": ["BookmarkA"]}
S: SUCCESS {}
C: RUN "CREATE (n {name:'Bob'})" {} {}
   PULL_ALL
S: SUCCESS {}
   SUCCESS {}
C: COMMIT
S: SUCCESS {"bookmark": "BookmarkB"}
C: BEGIN {"bookmarks": ["BookmarkB"]}
S: SUCCESS {}
C: RUN "MATCH (n) RETURN n.name AS name" {} {}
   PULL_ALL
S: SUCCESS {"fields": ["name"]}
   RECORD ["Bob"]
   SUCCESS {}
C: COMMIT
S: SUCCESS {"bookmark": "BookmarkC"}
