!: AUTO INIT
!: AUTO RESET
!: AUTO PULL_ALL

C: RUN "BEGIN" {"bookmark": "BookmarkA", "bookmarks": ["BookmarkA"]}
   PULL_ALL
S: SUCCESS {}
   SUCCESS {}
C: RUN "CREATE (n {name:'Bob'})" {}
   PULL_ALL
S: SUCCESS {}
   SUCCESS {}
C: RUN "COMMIT" {}
   PULL_ALL
S: SUCCESS {}
   SUCCESS {"bookmark": "BookmarkB"}
C: RUN "BEGIN" {"bookmark": "BookmarkB", "bookmarks": ["BookmarkB"]}
   PULL_ALL
S: SUCCESS {}
   SUCCESS {}
C: RUN "MATCH (n) RETURN n.name AS name" {}
   PULL_ALL
S: SUCCESS {"fields": ["name"]}
   RECORD ["Bob"]
   SUCCESS {}
C: RUN "COMMIT" {}
   PULL_ALL
S: SUCCESS {}
   SUCCESS {"bookmark": "BookmarkC"}
